-- SemanticDocs initial schema.
-- Flyway runs this once and records it in flyway_schema_history, so every developer
-- and every environment ends up with byte-identical structure.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    filename      VARCHAR(500) NOT NULL,
    content_type  VARCHAR(150),
    size_bytes    BIGINT       NOT NULL,
    storage_path  VARCHAR(1000) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    chunk_count   INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    indexed_at    TIMESTAMPTZ
);
CREATE INDEX idx_documents_user_status ON documents (user_id, status);

CREATE TABLE chunks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id  BIGINT  NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    chunk_index  INTEGER NOT NULL,
    content      TEXT    NOT NULL,
    char_start   INTEGER NOT NULL,
    char_end     INTEGER NOT NULL,
    page_number  INTEGER,
    UNIQUE (document_id, chunk_index)
);
CREATE INDEX idx_chunks_document ON chunks (document_id);

-- One embedding per chunk. The vector is stored as raw little-endian float32 bytes:
-- 768 floats = 3072 bytes. We keep it in its own table so that a "SELECT * FROM chunks"
-- during debugging does not drag megabytes of binary data along with it.
CREATE TABLE embeddings (
    chunk_id  BIGINT      NOT NULL PRIMARY KEY REFERENCES chunks (id) ON DELETE CASCADE,
    model     VARCHAR(120) NOT NULL,
    dimension INTEGER     NOT NULL,
    vector    BYTEA       NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    document_id BIGINT       REFERENCES documents (id) ON DELETE SET NULL,
    title       VARCHAR(300) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_conversations_user ON conversations (user_id, created_at DESC);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
    role            VARCHAR(20) NOT NULL,
    content         TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);

-- Which chunks the model was shown when it produced a given answer. This is what makes
-- "click the citation and jump to the source" possible.
CREATE TABLE message_citations (
    message_id BIGINT NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    chunk_id   BIGINT NOT NULL REFERENCES chunks (id) ON DELETE CASCADE,
    score      REAL   NOT NULL,
    rank       INTEGER NOT NULL,
    PRIMARY KEY (message_id, chunk_id)
);
